### ISSUE TITLE
resetDefaultPlaylistName

### ISSUE THREAD

**Issue by mp1pro** [Shawn-Williams/Jammming-CA#5]
Instead if hardcoding the default playList name in resetDefaultPlaylistName, we can reset it to its initial state like so
`this.setState({playlistName: this.state.playlistName});`

**Comment by Shawn-Williams** [comment]
Thank you. My original intent was to utilize the function to reset the this.state.playlistName to the original value on an onBlur event when the user clicked out of an empty input area. I don't believe setting playlistName to this.state.playlistName would work since the state is being changed during an onChange event. My thought process here is to prevent saving a playlist with no name, but to reset it to 'New Playlist'. 

Currently the method is unused as I am working to determine the best way to approach this and may change my thinking altogether as the problem I ran into was handlePlaylistSave was called before the state had a chance to update and was saving a nameless playlist nonetheless. Any suggestions would be greatly appreciated.

**Comment by mp1pro** [comment]
I understand now. Thanks for clarifying. Component life-cycles is your best approach. ref: https://reactjs.org/docs/react-component.html
For further help, consult an adviser at http://codecademy.com

**Comment by Shawn-Williams** [comment]
Thank you.
